export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}

export const ActionAvatar = {
  LOAD_AVATAR: 'LOAD_AVATAR_REQUEST',
  LOAD_SENTENCE: 'LOAD_SENTENCE_REQUEST',
  LOAD_USERINFO: 'LOAD_USERINFO_REQUEST',
  LOGIN_REFRESH: 'LOGIN_REFRESH',
  CLEAR_AVATAR: 'CLEAR_AVATAR'
}